### PR TITLE
compare vversion in the schduler

### PR DESCRIPTION
**Pull request by Michal-Babins**
Reconfigure how the scheduler considers version in the context of comparing workflows.

### CODE REVIEW

**Review by scanon — CHANGES_REQUESTED** [review]
I think this looks good, but we should add some tests and confirm that the behavior is the same before and after.

**Review by scanon — CHANGES_REQUESTED** [review]
Need to add one test and confirm if things are working as expected.

**Review by scanon — APPROVED** [review]

**Comment by aclum** [comment]
@scanon can we close this w/o merging since you've been fixing bugs in the version schedule comparisons?

**Comment by scanon** [comment]
> @scanon can we close this w/o merging since you've been fixing bugs in the version schedule comparisons?

I think so.  I will close it now.

**Pull request closed without merging**
